backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }

  - name: "executives"
    label: "Executives"
    folder: "src/content/executives"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "role", label: "Role", widget: "string" }
      - { name: "bio", label: "Bio", widget: "text" }
      - { name: "photo", label: "Photo", widget: "image" }

  - name: "faq"
    label: "FAQ"
    folder: "src/content/FAQ"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "question", label: "Question", widget: "string" }
      - { name: "answer", label: "Answer", widget: "string" }

  - name: "contact"
    label: "FAQ"
    folder: "src/content/FAQ"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "question", label: "Question", widget: "string" }
      - { name: "answer", label: "Answer", widget: "string" }

  - name: ""
    label: ""
    folder: "src/content/"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "", label: "", widget: "" }
      - { name: "", label: "", widget: "" }